# Generated by Django 5.1.7 on 2025-03-27 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_unique_repost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='posts.post'),
        ),
    ]
