# Generated by Django 5.1.7 on 2025-03-27 01:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_alter_post_repost_of'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_repost',
        ),
        migrations.RemoveField(
            model_name='post',
            name='repost_of',
        ),
        migrations.AddField(
            model_name='post',
            name='reposted_by',
            field=models.ManyToManyField(blank=True, related_name='reposts', to=settings.AUTH_USER_MODEL),
        ),
    ]
