# Generated by Django 5.1.7 on 2025-03-27 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_unique_repost_remove_post_repost_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='reposted_by',
        ),
        migrations.AddField(
            model_name='post',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='posts.post'),
        ),
    ]
