# Generated by Django 5.1.7 on 2025-04-04 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_match_game_id_alter_team_team_id'),
        ('posts', '0009_post_unique_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game', to='matches.match'),
        ),
    ]
