# Generated by Django 5.1.7 on 2025-04-07 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_game'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='post',
            name='unique_repost',
        ),
    ]
