# Generated by Django 5.1.7 on 2025-03-27 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='retweet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retweets', to='accounts.profile'),
        ),
    ]
