# Generated by Django 5.1.7 on 2025-03-27 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_profile_retweet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='retweet',
        ),
        migrations.AddField(
            model_name='profile',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='accounts.profile'),
        ),
    ]
