# Generated by Django 5.1.7 on 2025-03-27 01:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_profile_repost_repost'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='repost_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='accounts.profile'),
        ),
        migrations.DeleteModel(
            name='Repost',
        ),
    ]
