# Generated by Django 5.1.7 on 2025-04-12 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_notification_is_read'),
        ('posts', '0012_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='follow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.follow'),
        ),
        migrations.AddField(
            model_name='notification',
            name='like',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.like'),
        ),
        migrations.AddField(
            model_name='notification',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.post'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replay_noti', to='posts.post'),
        ),
    ]
