# Generated by Django 5.1.7 on 2025-03-20 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
