# Generated by Django 5.1.7 on 2025-03-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
