# Generated by Django 5.1.7 on 2025-03-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_clock',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='match',
            name='games_status',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='short_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
