# Generated by Django 5.1.7 on 2025-03-20 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_game_clock_match_games_status_team_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='games_status',
            new_name='game_status',
        ),
    ]
