# Generated by Django 5.1.7 on 2025-04-04 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_remove_match_id_remove_team_id_alter_match_game_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
