# Generated by Django 5.1.7 on 2025-04-09 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_match_game_id_alter_team_team_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_status_text',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
