# Generated by Django 5.1.7 on 2025-04-04 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_match_game_id_alter_team_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='game_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
