# Generated by Django 5.1.7 on 2025-04-11 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_match_game_status_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='box_score',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
